# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nhNGzBiTo23NX6u8yY3IzlX2_S4it9RS
"""

from google.colab import files

# Rasmlarni yuklash
uploaded = files.upload()

from PIL import Image
import matplotlib.pyplot as plt

# Yuklangan fayllarni ochish
for filename in uploaded.keys():
    # Rasmni ochish
    img = Image.open(filename)

    # Oq-qora tasvirga o'tkazish
    grayscale_img = img.convert("L")

    # Original va oq-qora tasvirni ko'rsatish
    plt.figure(figsize=(10, 5))

    # Original rasm
    plt.subplot(1, 2, 1)
    plt.title("Original")
    plt.imshow(img)
    plt.axis('off')

    # Oq-qora tasvir
    plt.subplot(1, 2, 2)
    plt.title("Oq-qora")
    plt.imshow(grayscale_img, cmap='gray')
    plt.axis('off')

    plt.show()